services:
  caddy:
    container_name: caddy
    image: docker.io/library/caddy:2-alpine
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - SIAintranet
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME}
      - SEARXNG_TLS=${SEARXNG_TLS}
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - SIAintranet
    volumes:
      - valkey-data2:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - SIAintranet
    depends_on:
      - redis
    volumes:
      - ./searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL}
      - SEARXNG_REDIS_URL=redis://redis:6379/0
      - DOCKER=true
      - SEARXNG_SECRET=${SEARXNG_SECRET}
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  ollama:
    container_name: ollama
    image: ollama/ollama:rocm
    runtime: amd
    restart: unless-stopped
    networks:
      - SIAintranet
    ports:                 # uncomment if you want to use 
      - "127.0.0.1:11435:11434"      # http://localhost:11434/ to diagnose ollama
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - DOCKER=true
      - AMD_VISIBLE_DEVICES=all
    devices:                # \
      - /dev/kfd            #  Optional if AMD Container Runtime Toolkit present
      - /dev/dri            # /
    security_opt:
      - seccomp=unconfined
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    runtime: amd
    restart: unless-stopped
    networks:
      - SIAintranet
    ports:                   # Removable when https working right
      - "3000:8080"
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>&format=json
      - WEBUI_URL=${WEBUI_URL}
      - WEB_SEARCH_ENGINE=searxng
      - OFFLINE_MODE=true
      - DOCKER=true
      - AMD_VISIBLE_DEVICES=all
    devices:                # \
      - /dev/kfd            #  Optional if AMD Container Runtime Toolkit present
      - /dev/dri            # /
    security_opt:
      - seccomp=unconfined

networks:
  SIAintranet:

volumes:
  caddy-data:
  caddy-config:
  valkey-data2:
  searxng-data:
  