# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
general:
  debug: false
  instance_name: "SearXNG Search"
  donation_url: false
  contact_url: false
  enable_metrics: false
  enabled_plugins:
    - "Hash plugin"
    - "Self Information"
    - "Tracker URL remover"
    - "Ahmia blacklist"
    - "Open Access DOI rewrite"
    - "Hostnames plugin"
    - "Unit converter plugin"
    - "Basic Calculator"

server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and *.yaml
  secret_key: "${SEARXNG_SECRET}"
  limiter: false # enable this when running the instance for a public usage on the internet
  image_proxy: true
  bind_address: "0.0.0.0"
  port: 8080
  method: "POST"

ui:
  static_use_hash: true
  default_themes: simple
  center_alignment: true
  hotkeys: default

search:
  safe_search: 1
  autocomplete: "duckduckgo"
  favicon_resolver: "duckduckgo"
  formats:
    - html
    - csv
    - json
    - rss
redis:
  url: redis://redis:6379/0

outgoing:
  useragent_suffix: ""
  request_timeout: 5.0
  max_request_timeout: 10.0

engines:
  - name: google
    engine: google
    shortcut: go
    use_mobile_ui: false
    disabled: false
  - name: startpage
    engine: startpage
    disabled: false
  - name: reddit
    engine: reddit
    shortcut: re
    disabled: false
    weight: 2
  - name: stackoverflow
    engine: stackoverflow
    shortcut: st
    disabled: false
  - name: github
    engine: github
    shortcut: gh
    disabled: false
  - name: duckduckgo_definitions
    engine: duckduckgo_definitions
    shortcut: def
    disabled: false
    weight: 2
